version: "3.8"

services:

  db:
    container_name: registry_db
    image: postgres
    restart: always
    # env_file:
    #   - .env
    ports:
      - 7865:5432
    volumes:
      - db:var/lib/postgresql/data
    # environment:
    #     - POSTGRES_USER=${POSTGRES_USER}
    #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #     - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
        - .env
    ports:
        - 7866:80
    # environment:
    #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
        - db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8080: 8080
  
volumes:
  data:
